### ISSUE TITLE
ensure consistency in construction of objects

### ISSUE THREAD

**Issue by sarxhlwalker** [CSC207-2022F-UofT/course-project-team-communify#66]
- where interactor is constructed (viewmodel or controller) 
- where input data is constructed (viewmodel or controller) 
- anything else? 

afaik we've been trying to keep consistent on our PRs as we go, but i'd like to make a final pass at some point to double check everything just in case.

**Comment by sarxhlwalker** [comment]
tl;dr: create interactor and input data in controller; in viewmodel, just create the presenter and controller.

**Comment by rafaelgacesa** [comment]
fixed in https://github.com/CSC207-2022F-UofT/course-project-team-communify/pull/73, https://github.com/CSC207-2022F-UofT/course-project-team-communify/pull/72
