### ISSUE TITLE
TestStopQueue() will erratically pass or fail.

### ISSUE THREAD

**Issue by chrstinalin** [CSC207-2022F-UofT/course-project-team-communify#82]
I'm not familiar enough with what's occurring in this test but, based purely off assumptions, I'd presume it's due to .sleep() ending before the test song has finished playing due to the playback beginning later than expected.

**Comment by rafaelgacesa** [comment]
Yeah, I picked 5.5 seconds as the absolute minimum sleep for that to work, so it’s possible I didn’t try enough times and it should be 6 or 7 seconds. Hopefully that will fix the problem.
